"""Add summary_up_to_message to conversations

Revision ID: 52e28b635169
Revises: 003_customer_constraint
Create Date: 2026-01-21 11:17:44.684008+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e28b635169'
down_revision: Union[str, None] = '003_customer_constraint'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary_up_to_message', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'summary_up_to_message')
    # ### end Alembic commands ###
