"""Rename summary_up_to_message to total_message_count and last_summary_at

Revision ID: a597e51799f9
Revises: 52e28b635169
Create Date: 2026-01-22 15:11:26.571230+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a597e51799f9'
down_revision: Union[str, None] = '52e28b635169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('total_message_count', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('last_summary_at', sa.Integer(), nullable=True))
    op.drop_column('conversations', 'summary_up_to_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary_up_to_message', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('conversations', 'last_summary_at')
    op.drop_column('conversations', 'total_message_count')
    # ### end Alembic commands ###
