"""Add address, language, notes to Customer model

Revision ID: cec494bf4270
Revises: a597e51799f9
Create Date: 2026-01-22 15:43:04.374023+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec494bf4270'
down_revision: Union[str, None] = 'a597e51799f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('address', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('language', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'notes')
    op.drop_column('customers', 'language')
    op.drop_column('customers', 'address')
    # ### end Alembic commands ###
